app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),  
    path('srv/',include(('srv.urls','srv'), namespace='srv')),  
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

inv/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from inv.views import *
from .views import *

urlpatterns = [
    path('dispositivo/',DispositivoView.as_view(), name='dispositivo_list'),    
    path('dispositivo/new',DispositivoNew.as_view(), name='dispositivo_new'),
    path('dispositivo/edit/<int:pk>',DispositivoEdit.as_view(), name='dispositivo_edit'),
    path('dispositivo/delete/<int:pk>',DispositivoDel.as_view(), name='dispositivo_del'),
    
    path('persona/',PersonaView.as_view(), name='persona_list'),    
    path('persona/new',PersonaNew.as_view(), name='persona_new'),
    path('persona/edit/<int:pk>',PersonaEdit.as_view(), name='persona_edit'),
    path('persona/delete/<int:pk>',PersonaDel.as_view(), name='persona_del'),
]

inv/models.py
from django.db import models
from bases.models import ClaseModelo
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

import uuid


# Create your models here.

class Persona(ClaseModelo):
    class Rol(models.TextChoices):
        dinamizador="dinamizador",_("Dinamizador")
        technic="tecnico",_("Técnico(a)")
        usuario="usuario",_("Usuario sena")
        contratista="contratista",_("Contratista")
        anonimo="anonimo",_("Anónimo")

    cedula=models.CharField(max_length=20,help_text="Cédula")
    celular=models.CharField(max_length=10,help_text="Número de celular",blank=True,null=True)
    user=models.OneToOneField(User,on_delete=models.CASCADE,verbose_name='Usuario')
    rol=models.CharField(verbose_name='Rol',max_length=15,choices=Rol,default=Rol.anonimo)
    
    def __str__(self):
        return f'{self.user.get_full_name().capitalize()}'
    
    class Meta:
        verbose_name_plural = 'Personas'


class Dispositivo(ClaseModelo):
    class Regional(models.TextChoices):
        boyaca="15",_("Boyaca")
    
    class Sede(models.TextChoices):
        cegafe="15",_("Cegafe")
        santaclara="16",_("Santa clara")
        ape="17",_("APE")
        itedris="18",_("ITEDRIS")
        gastronomia="19",_("Gastronomia")
        
    class Tipos(models.TextChoices):
        tipo4="4",_("Tipo 4")
        
    class Tipo(models.TextChoices):
        escritorio="escritorio",_("Escritorio")
        portatil="portatil",_("Portatil")
        impresora="impresora",_("Impresora")
        escaner="escaner",_("Escaner")
        tv="tv",_("Televisor")

    class Status(models.TextChoices):
        Creado="creado",_("Creado")        
        Ejecutado="ejecutado",_("Ejecutado")
        mantenimiento="mantenimiento",_("Mantenimiento")
        Facturado="facturado",_("Facturado")
        no_show="no_show",_("NO SHOW")
        
    class Salon(models.TextChoices):
        _default="Default",_("Default")
        _406="406",_("Piso 406")
        _306="306",_("Piso 2 306")     
        _107="107",_("Piso 1")
    
    class Ubicacion(models.TextChoices):
        _default="Default",_("Default")
        _406="406",_("-- 406")
        _306="306",_("-- 306")     
        _107="107",_("-- 107")       
    
    class Legalizado(models.TextChoices):        
        sin_legalizar="sin legalizar",_("Sin legalizar")
        legalizado="legalizado",_("Legalizado")
    
    fecha=models.DateTimeField(null=True,blank=True,verbose_name='Fecha:')
    descripcion=models.CharField(max_length=50,verbose_name='Descripción:')
    descripcionActual=models.CharField(max_length=250,blank=True,null=True,verbose_name='Descripción actual')
    
    
    placa=models.CharField(verbose_name='Placa',max_length=12,blank=True,null=True)     
    placa6=models.CharField(verbose_name='Placa6',max_length=6,blank=True,null=True)
    serial=models.CharField(max_length=10,blank=True,null=True)
    modelo=models.CharField(max_length=50,blank=True,null=True)
    
    tipoElemento=models.CharField(max_length=50,blank=True,null=True,verbose_name='Tipo de elemento')
    unidad=models.CharField(max_length=50,blank=True,null=True)
    discoDuro=models.CharField(max_length=50,blank=True,null=True,verbose_name='Disco duro')
    memoria=models.CharField(max_length=50,blank=True,null=True)
    ram=models.CharField(max_length=50,blank=True,null=True)
    pantalla=models.CharField(max_length=50,blank=True,null=True)
    procesador=models.CharField(max_length=50,blank=True,null=True)
    unidadLectora=models.CharField(max_length=50,blank=True,null=True,verbose_name='Unidad lectora')
    marca=models.CharField(max_length=50,blank=True,null=True)
    sistemaOperativo=models.CharField(max_length=50,blank=True,null=True,verbose_name='Sistema operativo')
    guayaSeguridad=models.CharField(max_length=50,blank=True,null=True,verbose_name='Guaya de seguridad')
    mouse=models.CharField(max_length=100,blank=True,null=True)
    
    observaciones=models.CharField(max_length=100,blank=True,null=True)
    
    
    salon=models.CharField(verbose_name='Salon',max_length=15,choices=Salon,default=Salon._default)
    ubicacion=models.CharField(verbose_name='Ubicacion',max_length=15,choices=Ubicacion,default=Ubicacion._default)
    numero_registo=models.UUIDField(default=uuid.uuid4,max_length=80)
    type=models.CharField(verbose_name='Tipo',max_length=15,choices=Tipo,blank=True,null=True)
    persona=models.ForeignKey(Persona,on_delete=models.CASCADE,blank=True,null=True,verbose_name='Cuentadante')
    cuentadanteNumber=models.CharField(max_length=10,blank=True,null=True,verbose_name='N¬identificación')
    status=models.CharField(verbose_name='Status',max_length=15,choices=Status,default=Status.Creado)
    
    
    regional=models.CharField(verbose_name='Regional',max_length=15,choices=Regional,default=Regional.boyaca)
    sede=models.CharField(verbose_name='Sede',max_length=15,choices=Sede,blank=True,null=True)
    attribute=models.CharField(verbose_name='Atributos',max_length=250,blank=True,null=True)
    
    types=models.CharField(verbose_name='Tipo', choices=Tipos,blank=True,null=True)
    valor=models.DecimalField(verbose_name='Valor',max_digits=14, decimal_places=2, default=0.0)
    
    class Meta:
        verbose_name_plural="Dispositivos"

    def __str__(self):
        return f'{self.descripcion}, Placa: {self.placa}'
    
    def save(self):
        # self.descripcion=self.descripcion.upper()
        return super().save()

inv/forms.py
from django import forms

from .models import *

class DispositivoForm(forms.ModelForm):
    
    attribute = forms.CharField(label="Atributos", required=False, widget=forms.Textarea(
        attrs={'class':'form-control', 'rows': 10, 'placeholder':'Descripción actual',
        }
    ), min_length=10, max_length=250)
    
    
    observaciones = forms.CharField(label="Observaciones", required=False, widget=forms.Textarea(
        attrs={'class':'form-control', 'rows': 3, 'placeholder':'Observaciones',
        }
    ), min_length=10, max_length=100)
    
    
    descripcionActual = forms.CharField(label="Descripción actual", required=False, widget=forms.Textarea(
        attrs={'class':'form-control', 'rows': 5, 'placeholder':'Descripción actual',
        }
    ), min_length=10, max_length=250)
    
    class Meta:
        model=Dispositivo
        fields=[
            'fecha',
            'descripcion',
            'descripcionActual',
            'estado',
            'placa',
            'placa6',
            'serial',
            'modelo',
            'tipoElemento',
            'unidad',
            'discoDuro',
            'memoria',
            'ram',
            'pantalla',
            'procesador',
            'unidadLectora',
            'marca',
            'sistemaOperativo',
            'guayaSeguridad',
            'mouse',
            'observaciones',
            'salon',
            'ubicacion',
            'type',
            'persona',
            'cuentadanteNumber',
            'status',
            'regional',
            'attribute',
            'types',
            'valor',
            
            ]
        exclude=['numero_registro']
        labels={'descripcion':"Descripción:",
                "estado":"Estado",
                "placa6":"Placa",
                'tipoElemento':'Tipo de elemento:'

                }
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})


class PersonaForm(forms.ModelForm):
    
    class Meta:
        model=Persona
        fields=['cedula','estado']
        # exclude=['numero_regis']
        labels={"cedula":"Cédula","estado":"Estado"}
        widget={'cedula': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})

inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.messages.views import SuccessMessageMixin

from bases.views import SinPrivilegios
from .models import *
from .forms import *

# Create your views here.

class DispositivoView(SinPrivilegios, generic.ListView):
    permission_required="inv.view_dispositivo"
    model=Dispositivo
    template_name="inv/dispositivo_list.html"
    context_object_name="obj"
    ordering = ['-id']
    
class DispositivoNew(SuccessMessageMixin,SinPrivilegios, generic.CreateView):
    permission_required="inv.add_dispositivo"
    model=Dispositivo
    template_name="inv/dispositivo_form.html"
    context_object_name = "obj"
    form_class=DispositivoForm
    success_url=reverse_lazy("inv:dispositivo_list")
    success_message="Dispositivo creada satisfactoriamente"

    def form_invalid(self, form):
        response = super().form_invalid(form)
        print('**',response  )

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class DispositivoEdit(SuccessMessageMixin,SinPrivilegios, generic.UpdateView):
    permission_required="inv.change_dispositivo"
    model=Dispositivo
    template_name="inv/dispositivo_form.html"
    context_object_name = "obj"
    form_class=DispositivoForm
    success_url=reverse_lazy("inv:dispositivo_list")
    success_message="Dispositivo actualizada satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user
        return super().form_valid(form)

class DispositivoDel(SuccessMessageMixin,SinPrivilegios, generic.DeleteView):
    permission_required="inv.delete_dispositivo"
    model=Dispositivo
    template_name='inv/dispositivo_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:dispositivo_list")
    success_message="Dispositivo eliminado satisfactoriamente"


class PersonaView(SinPrivilegios, generic.ListView):
    permission_required="inv.view_persona"
    model=Persona
    template_name="persona/persona_list.html"
    context_object_name="obj"
    
class PersonaNew(SuccessMessageMixin,SinPrivilegios, generic.CreateView):
    permission_required="inv.add_persona"
    model=Persona
    template_name="persona/persona_form.html"
    context_object_name = "obj"
    form_class=PersonaForm
    success_url=reverse_lazy("inv:persona_list")
    success_message="Persona creada satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class PersonaEdit(SuccessMessageMixin,SinPrivilegios, generic.UpdateView):
    permission_required="inv.change_persona"
    model=Persona
    template_name="persona/persona_form.html"
    context_object_name = "obj"
    form_class=PersonaForm
    success_url=reverse_lazy("inv:persona_list")
    success_message="Persona actualizada satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user
        return super().form_valid(form)

class PersonaDel(SuccessMessageMixin,SinPrivilegios, generic.DeleteView):
    permission_required="inv.delete_persona"
    model=Persona
    template_name='persona/persona_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:persona_list")
    success_message="Persona eliminado satisfactoriamente"

inv/templates/inv/dispositivo_form.html
{% extends 'base/base.html' %}
{% block page_content %}
<form method="POST" >
    {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} equipo tecnológico
                        </div>

                        <div class="dropdown-divider"></div>


                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger">
                                    <span class="fa fa-save"></span> Guardar
                                </button>
                                <a href="{% url 'inv:dispositivo_list' %}" class="btn btn-success">
                                    <span class="fa fa-undo"></span> Cancelar
                                </a>
                            </div>
                        </div>

                        <div class="dropdown-divider"></div>
                        
                        <div class="row">                            
                            <div class="col-lg-3 col-md-6">
                                <div class="form-group">                                    
                                    {{form.fecha.label}}
                                    {{form.fecha}}
                                </div>
                            </div> 
                            <div class="col-lg-3 col-md-6">
                                <div class="form-group">
                                    {{form.descripcion.label}}
                                    {{form.descripcion}}
                                    <!-- <input type="text" name="descripcion" maxlength="50" 
                                    class="form-control" required id="id_descripcion" placeholder="Descripción"
                                    value="{#% if obj %#} {#{ obj.descripcion }#} {#% endif %#}"> -->
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6">
                                <div class="form-group">
                                    {{form.descripcionActual.label}}
                                    {{form.descripcionActual}}
                                </div>
                            </div>
                            
                            <div class="col-lg-1 col-md-6">
                                <div class="form-group">                                    
                                    {{form.estado.label}}
                                    {{form.estado}}
                                </div>
                            </div> 
                            <div class="col-lg-2 col-md-6">
                                <div class="form-group">                                    
                                    {{form.placa.label}}:
                                    {{form.placa}}
                                </div>
                            </div> 
                            <div class="col-lg-2 col-md-6">
                                <div class="form-group">                                    
                                    {{form.placa6.label}}:
                                    {{form.placa6}}
                                </div>
                            </div> 
                            <div class="col-lg-3 col-md-12">
                                <div class="form-group">                                    
                                    {{form.serial.label}}:
                                    {{form.serial}}
                                </div>
                            </div> 
                            <div class="col-lg-3 col-md-12">
                                <div class="form-group">                                    
                                    {{form.modelo.label}}:
                                    {{form.modelo}}
                                </div>
                            </div> 
                            <div class="col-lg-3 col-md-12">
                                <div class="form-group">                                    
                                    {{form.type.label}}:
                                    {{form.type}}
                                </div>
                            </div> 
                            <div class="col-lg-3 col-md-12">
                                <div class="form-group">                                    
                                    {{form.persona.label}}:
                                    {{form.persona}}
                                </div>
                            </div> 
                            <div class="col-lg-3 col-md-12">
                                <div class="form-group">                                    
                                    {{form.cuentadanteNumber.label}}:
                                    {{form.cuentadanteNumber}}
                                </div>
                            </div> 

                            <div class="col-lg-2 col-md-12">
                                <div class="form-group">                                    
                                    {{form.tipoElemento.label}}
                                    {{form.tipoElemento}}
                                </div>
                            </div> 
                            
                            <div class="col-lg-3 col-md-12">
                                <div class="form-group">                                    
                                    {{form.salon.label}}:
                                    {{form.salon}}
                                </div>
                            </div> 

                            <div class="col-lg-3 col-md-12">
                                <div class="form-group">                                    
                                    {{form.ubicacion.label}}:
                                    {{form.ubicacion}}
                                </div>
                            </div> 


                            <div class="col-lg-2 col-md-12">
                                <div class="form-group">                                    
                                    {{form.unidad.label}}:
                                    {{form.unidad}}
                                </div>
                            </div> 

                            
                            <div class="col-lg-2 col-md-12">
                                <div class="form-group">                                    
                                    {{form.discoDuro.label}}:
                                    {{form.discoDuro}}
                                </div>
                            </div> 

                            <div class="col-lg-2 col-md-12">
                                <div class="form-group">                                    
                                    {{form.memoria.label}}:
                                    {{form.memoria}}
                                </div>
                            </div> 
                            <div class="col-lg-2 col-md-12">
                                <div class="form-group">                                    
                                    {{form.ram.label}}:
                                    {{form.ram}}
                                </div>
                            </div> 
                            <div class="col-lg-6 col-md-6">
                                <div class="form-group">                                    
                                    {{form.pantalla.label}}:
                                    {{form.pantalla}}
                                </div>
                            </div> 

                            <div class="col-lg-6 col-md-6">
                                <div class="form-group">                                    
                                    {{form.procesador.label}}:
                                    {{form.procesador}}
                                </div>
                            </div> 

                            <div class="col-lg-3 col-md-12">
                                <div class="form-group">                                    
                                    {{form.unidadLectora.label}}:
                                    {{form.unidadLectora}}
                                </div>
                            </div> 


                            <div class="col-lg-3 col-md-6">
                                <div class="form-group">                                    
                                    {{form.marca.label}}:
                                    {{form.marca}}
                                </div>
                            </div> 

                            
                            <div class="col-lg-3 col-md-6">
                                <div class="form-group">                                    
                                    {{form.sistemaOperativo.label}}:
                                    {{form.sistemaOperativo}}
                                </div>
                            </div> 


                            <div class="col-lg-2 col-md-6">
                                <div class="form-group">                                    
                                    {{form.guayaSeguridad.label}}:
                                    {{form.guayaSeguridad}}
                                </div>
                            </div> 


                            <div class="col-lg-3 col-md-6">
                                <div class="form-group">                                    
                                    {{form.mouse.label}}:
                                    {{form.mouse}}
                                </div>
                            </div> 


                            <div class="col-lg-4">
                                <div class="form-group">                                    
                                    {{form.observaciones.label}}:
                                    {{form.observaciones}}
                                </div>
                            </div> 

                            <div class="col-lg-6 col-md-6">
                                <div class="form-group">                                    
                                    {{form.status.label}}:
                                    {{form.status}}
                                </div>
                            </div> 


                            <div class="col-lg-3 col-md-6">
                                <div class="form-group">                                    
                                    {{form.regional.label}}:
                                    {{form.regional}}
                                </div>
                            </div> 

                            
                            <div class="col-lg-6 col-md-6">
                                <div class="form-group">                                    
                                    {{form.attribute.label}}:
                                    {{form.attribute}}
                                </div>
                            </div> 

                               
                            <div class="col-lg-2 col-md-6">
                                <div class="form-group">                                    
                                    {{form.types.label}}:
                                    {{form.types}}
                                </div>
                            </div> 

                            <div class="col-lg-2 col-md-6">
                                <div class="form-group">                                    
                                    {{form.valor.label}}:
                                    {{form.valor}}
                                </div>
                            </div> 
                            
                            
                            
                            

                        </div>

                        <div class="dropdown-divider"></div>


                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger">
                                    <span class="fa fa-save"></span> Guardar
                                </button>
                                <a href="{% url 'inv:dispositivo_list' %}" class="btn btn-success">
                                    <span class="fa fa-undo"></span> Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block js_page %}
<script>
     $("#id_fecha").datetimepicker({
        format: 'd/m/Y',
        timepicker:false, 
    });
</script>
{% endblock %}

inv/templates/inv/dispositivo_list.html
{% extends 'base/base.html' %}
{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de dispositivos</h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones</div>
        <a class="dropdown-item" href="{% url 'inv:dispositivo_new' %}"><i class="far fa-calendar-plus"></i> Nuevo</a>
        <!-- <a class="dropdown-item" href="#">Otra acción</a>   -->
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Imprimir</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No hay dispositivos</div>
    {% else %}
    <table class="table table-striped table-hover">
        <thead>
            <th class="all">Acciones</th>
            <th>Id</th>
            <th>Descripción</th>
            <th>Tipo</th>
            <th>Estado</th>
            <th>F. Creado</th>
            <th>F. Modif.</th>
        </thead>
        <tbody>
            {% for item in obj %}
            <tr>
              <td>
                <a href="{% url 'inv:dispositivo_edit' item.id %}" class="btn btn-warning btn-circle" role="button">
                  <i class="far fa-edit"> </i>
                </a> 
                <a href="{#% url 'inv:dispositivo_del' item.id %#}" class="btn btn-danger btn-circle" role="button">
                  <i class="far fa-trash-alt"></i>
                </a>
              </td>
              <td>{{ item.id }}</td>
              <td>{{ item.descripcion }}</td>
              <td>{{ item.type | upper }}</td>
              <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
              <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
              <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>                  
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function () {
    $('.table').DataTable(
      {
        paging: false,
        scrollCollapse: true,
        scrollY: '250px',
        scrollX: true,
        responsive: true,
        language: {
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ registros",
          "sZeroRecords": "No se encontraron resultados",
          "sEmptyTable": "Ningún dato disponible en esta tabla",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
          },
          "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
        }
      }
    );
  });
</script>
{% endblock %}