app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),  
    path('srv/',include(('srv.urls','srv'), namespace='srv')),  
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

srv/urls.py
from django.urls import path

from srv.views import *
from .views import *

urlpatterns = [
    path('servicio/',ServicioView.as_view(), name='servicio_list'),    
    path('servicio/new',ServicioNew.as_view(), name='servicio_new'),
    path('servicio/edit/<int:pk>',ServicioEdit.as_view(), name='servicio_edit'),
    # path('servicio/delete/<int:pk>',ServicioDel.as_view(), name='servicio_del'),
    path('',nuevoServicio, name='nuevo_servicio'),
    path('servicio/gracias/',nuevoServicio, name='gracias'),
]

srv/models.py
from django.db import models
from bases.models import ClaseModelo
from django.utils.translation import gettext_lazy as _
# from django.contrib.auth.models import User
from inv.views import Dispositivo,Persona

import uuid
# Create your models here.

class Servicio(ClaseModelo):
    class Medio_pago(models.TextChoices):
        CONTADO = "CONTADO", _("Contado")
        CREDITO = "CREDITO", _("Crédito")
        TRANSFERENCIA = "TRANSFERENCIA", _("Transferencia")

    class Status(models.TextChoices):
        solicitado = "solicitado", _("solicitado")
        Creado = "creado", _("Creado")
        Creado_por = "creado_por", _("Creado por usuario")        
        Ejecutado = "ejecutado", _("Ejecutado")
        proceso = "proceso", _("En proceso")
        terminado = "terminado", _("Terminado")
        noFueNecesario = "noFueNecesario", _("No fue necesario")
        
    
    class Legalizado(models.TextChoices):        
        sin_legalizar = "sin legalizar", _("Sin legalizar")
        Legalizado = "legalizado", _("Legalizado")

    class Sede(models.TextChoices):
        cegafe="15",_("Cegafe")
        santaclara="16",_("Santa clara")
        ape="17",_("APE")
        itedris="18",_("ITEDRIS")
        gastronomia="19",_("Gastronomia")

    fecha=models.DateTimeField(null=True,blank=True)
    numero_registro=models.UUIDField(default=uuid.uuid4,max_length=80,verbose_name="Número de registro")
    content=models.TextField(verbose_name="Problema a reportar",blank=True,null=True,max_length=500)
    technic=models.ForeignKey(Persona, on_delete=models.CASCADE,verbose_name="Técnico(a)",blank=True,null=True)    
    image=models.ImageField(verbose_name="Imagen",upload_to="services",blank=True,null=True)
    
    dispositive=models.ForeignKey(Dispositivo,on_delete=models.CASCADE,max_length=50,verbose_name='Equipo tecnológico',blank=True,null=True)
    
    isComputer=models.BooleanField(verbose_name='Computador',default=False)
    isTv=models.BooleanField(verbose_name='Es TV?',default=False)
    isEmail=models.BooleanField(verbose_name='Es Email?',default=False)
    isVideoConferencia=models.BooleanField(verbose_name='Es video conferencia?',default=False)
    isProblemRed=models.BooleanField(verbose_name='Red',default=False)
    isScanner=models.BooleanField(verbose_name='Escaner',default=False)
    isPrinter=models.BooleanField(verbose_name='Impresora',default=False)
    isDb=models.BooleanField(verbose_name='¿Problema en base de datos?',default=False)
    isKeyboard=models.BooleanField(verbose_name='Teclado',default=False)
    isCamera=models.BooleanField(verbose_name='Cámara',default=False)
    isWifi=models.BooleanField(verbose_name='Wifi',default=False)
    isMicrophone=models.BooleanField(verbose_name='Microfono',default=False)
    isMouse=models.BooleanField(verbose_name='Ratón',default=False)
    isFileLost=models.BooleanField(verbose_name='¿Archivos perdidos?',default=False)
    isLaptopMedical=models.BooleanField(verbose_name='Equipo en mantenimiento',default=False)
    isPantallaAzul=models.BooleanField(verbose_name='Pantalla azul',default=False)
    isPowerOff=models.BooleanField(verbose_name='No enciende?',default=False)
    isAudio=models.BooleanField(verbose_name='Es Audio?',default=False)
    isMantenimiento=models.BooleanField(verbose_name='Solicita mantenimiento',default=False)
    
    
    qualification=models.PositiveSmallIntegerField(verbose_name='Calificacion',default=0, blank=True,null=True)
    status=models.CharField(max_length=15,choices=Status,default=Status.Creado,help_text= "Status",blank=True,null=True)
    email=models.EmailField(max_length=50,blank=True,null=True)
    
    sede=models.CharField(verbose_name='Sede',max_length=15,choices=Sede,blank=True,null=True)
    #TODO
    #es urgente
    #prioridad
    

    def __str__(self):
        return f'{self.fecha}'
    
    def save(self):
        super(Servicio,self).save()

    class Meta:
        verbose_name_plural = 'Servicios'

srv/forms.py
from django import forms
from .models import Servicio
from inv.views import Persona


class ServicioForm(forms.ModelForm):
    
    # name = forms.CharField(label="Nombre", required=True, widget=forms.TextInput(
    #     attrs={'class':'form-control', 'placeholder':'Escribe tu nombre'}
    # ), min_length=3, max_length=100)
    email = forms.EmailField(label="Email", required=True, widget=forms.EmailInput(
        attrs={'class':'form-control', 'placeholder':'Escribe tu email'}
    ), min_length=8, max_length=50)
    content = forms.CharField(label="Contenido", required=True, widget=forms.Textarea(
        attrs={'class':'form-control', 'rows': 3, 'placeholder':'Escribe tu mensaje',
        }
    ), min_length=10, max_length=500)
    
    technic = forms.ModelChoiceField(required=False,
        queryset=Persona.objects.filter(rol=Persona.Rol.technic,estado=True).order_by('user')
    )
    
    class Meta:
        model=Servicio
        fields=['fecha',
                'content',
                'technic',
                'image',
                'dispositive',
                'isComputer',
                'isTv',
                'isEmail',
                'isVideoConferencia',
                'isProblemRed',
                'isScanner',
                'isPrinter',
                'isDb',
                'isKeyboard',
                'isCamera',
                'isWifi',
                'isMicrophone',
                'isMouse',
                'isFileLost',
                'isLaptopMedical',
                'isPantallaAzul',
                'isPowerOff',
                'isAudio',
                'isMantenimiento',
                'qualification',
                'status',
                'email',
            ]
        exclude=['numero_registro']
        labels={'fecha':"Fecha", "technic":"Técnico(a)"}
        # widget={'email': forms.EmailField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})
        self.fields['fecha'].widget.attrs['autocomplete'] = "off"
        self.fields['content'].widget.attrs['autofocus'] = "true"
        self.fields['isComputer'].widget.attrs['class'] = "form-check-input"
        self.fields['isProblemRed'].widget.attrs['class'] = "form-check-input"
        self.fields['isScanner'].widget.attrs['class'] = "form-check-input"
        self.fields['isPrinter'].widget.attrs['class'] = "form-check-input"
        self.fields['isMantenimiento'].widget.attrs['class'] = "form-check-input"
        self.fields['isTv'].widget.attrs['class'] = "form-check-input"
        self.fields['isComputer'].widget.attrs['class'] = "form-check-input"
        self.fields['isTv'].widget.attrs['class'] = "form-check-input"
        self.fields['isEmail'].widget.attrs['class'] = "form-check-input"
        self.fields['isVideoConferencia'].widget.attrs['class'] = "form-check-input"
        self.fields['isProblemRed'].widget.attrs['class'] = "form-check-input"
        self.fields['isScanner'].widget.attrs['class'] = "form-check-input"
        self.fields['isPrinter'].widget.attrs['class'] = "form-check-input"
        self.fields['isDb'].widget.attrs['class'] = "form-check-input"
        self.fields['isKeyboard'].widget.attrs['class'] = "form-check-input"
        self.fields['isCamera'].widget.attrs['class'] = "form-check-input"
        self.fields['isWifi'].widget.attrs['class'] = "form-check-input"
        self.fields['isMicrophone'].widget.attrs['class'] = "form-check-input"
        self.fields['isMouse'].widget.attrs['class'] = "form-check-input"
        self.fields['isFileLost'].widget.attrs['class'] = "form-check-input"
        self.fields['isLaptopMedical'].widget.attrs['class'] = "form-check-input"
        self.fields['isPantallaAzul'].widget.attrs['class'] = "form-check-input"
        self.fields['isPowerOff'].widget.attrs['class'] = "form-check-input"
        self.fields['isAudio'].widget.attrs['class'] = "form-check-input"
        self.fields['isMantenimiento'].widget.attrs['class'] = "form-check-input"
        

srv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.urls import reverse
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required

from datetime import datetime
from bases.views import SinPrivilegios
from .models import *
from .forms import *
from inv.views import Persona
# Create your views here.

class VistaBaseCreate(SuccessMessageMixin,SinPrivilegios, generic.CreateView):
    context_object_name = 'obj'
    success_message="Servicio agregado satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class VistaBaseEdit(SuccessMessageMixin,SinPrivilegios, generic.UpdateView):
    context_object_name = 'obj'
    success_message="Servicio actualizado satisfactoriamente"
    
    def form_valid(self, form):
        form.instance.um = self.request.user
        return super().form_valid(form) 

class ServicioDetailView(SinPrivilegios, generic.DetailView):
    permission_required = "srv.view_servicio"
    model = Servicio
    template_name = "servicio/servicio_detail.html"
    context_object_name = "obj"

class ServicioView(SinPrivilegios, generic.ListView):
    permission_required = "srv.view_servicio"
    model = Servicio
    template_name = "servicio/servicio_list.html"
    context_object_name = "obj"
    ordering = ['-fc']
    # serializer_class = ServicioSerializer
    # filter_backends = (filters2.DjangoFilterBackend,)
    # filterset_fields = ('fecha', 'factura')
    
    def get_context_data(self, **kwargs):    
        context = super().get_context_data(**kwargs)
        # context["form"] = ServicioFormFilter(self.request.GET)
        return context
    def get_queryset(self):        
        if self.request.user.is_superuser:            
            return super().get_queryset()        
        p=Persona.objects.filter(user=self.request.user).first()
        if p.rol == Persona.Rol.technic:            
            return super().get_queryset().filter(technic=p)

def nuevoServicio(request):
    template_name="servicio/servicio_form.html"
    reg=Servicio(fecha=datetime.now())
    
    form=ServicioForm()
    context={'form': form,'obj': reg}
    if request.method == 'POST':
        form=ServicioForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect(reverse('srv:nuevo_servicio')+"?ok") # render(request,"servicio/servicio_detail.html",{'obj':s})
    
    if request.method == 'GET' and 'ok' in request.GET:
    
        print('nuevo***')
        # return render(request,template_name,context)
        # return redirect(reverse('srv:nuevo_servicio'))

    return render(request,template_name,context)

class ServicioNew(VistaBaseCreate):
    model=Servicio
    template_name="servicio/servicio_form.html"
    form_class=ServicioForm
    success_url=reverse_lazy("srv:servicio_list")
    permission_required="srv.add_servicio"
    
    def get(self, request):        
        p=Persona.objects.get(user=self.request.user)
        reg=Servicio(fecha=datetime.now(),technic=p, email=p.user.email)
        form=ServicioForm(instance=reg)            
        context={'form': form,'obj': reg,'p':p}
        return render(request, self.template_name, context)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        # perfil=PerfilConductor.objects.filter(usuario = self.request.user).first()
        # if perfil and self.request.user.is_superuser == False:
        #     vehiculo = Vehiculo.objects.get(placa=perfil.vehiculo.pk)
        # context ['obj'] = Servicio(fecha = datetime.now())
        return context
    
    def form_invalid(self, form, **kwargs):
        context = super().get_context_data(**kwargs)
        return render(self.request, self.template_name, context)
    
    def form_valid(self, form):
        form.instance.uc = self.request.user        
    #     if perfil:=PerfilConductor.objects.filter(usuario = self.request.user).first():
    #         vehiculo = Vehiculo.objects.get(placa=perfil.vehiculo.pk)
    #         if self.request.user.is_superuser and vehiculo :
    #             form.instance.cedula = 1000000
    #             form.instance.conductor = 'Creado por superuser'                
    #             form.instance.placa = perfil.vehiculo_id
    #         # si es conductor
    #         elif vehiculo :                
    #             form.instance.cedula = vehiculo.conductor.cedula
    #             form.instance.conductor = vehiculo.conductor.nombre
    #             form.instance.placa = vehiculo.placa
            
        return super().form_valid(form)

class ServicioEdit(VistaBaseEdit):
    permission_required="srv.change_Servicio"
    model=Servicio
    template_name="servicio/servicio_form.html"
    form_class=ServicioForm
    success_url=reverse_lazy("srv:servicio_list")
    
    
    def get(self, request, pk):
        try:
            reg = (Servicio.objects.get(id=pk))            
            # perfil = PerfilConductor.objects.filter(usuario = self.request.user).first()
            # # primer validacion id debe pertenecer reg.vehiculo.placa y no es super user
            # if perfil and reg and self.request.user.is_superuser == False:
            #     vehiculo = Vehiculo.objects.get(placa=perfil.vehiculo)
            #     if vehiculo.placa != reg.vehiculo.placa:                                   
            #         messages.success(request,'Id no pertenece al conductor') 
            #         return redirect('elim:gasto_list')
            # Segunda valiacion: estado del registro                
            # if reg and self.request.user.is_superuser == False and reg.estado_aceptacion in[True, False]:                
            #     state_text ='Ninguno'
            #     if reg.estado_aceptacion is None:
            #         state_text= 'Por revisar'                    
            #     elif bool(reg.estado_aceptacion):
            #         state_text = 'Aceptado. No requiere edición'
            #     else: 
            #         state_text = 'Rechazado'
            #     messages.success(request,f'Gasto tiene un estado {state_text}') 
            #     return redirect('elim:gasto_list')

            form = ServicioForm (instance=reg)            
            context = {'form': form,'obj': reg}
            return render(request, self.template_name, context)
        except Servicio.DoesNotExist:
            # return JsonResponse({'error': 'Gasto del conductor no encontrado'}, status=404)
            return render(request, self.template_name, context)
        except Exception as e:
            # Log the error here
            # return JsonResponse({'error': 'An unexpected error occurred'}, status=500)
            return render(request, self.template_name, context)

    def form_invalid(self, form,  **kwargs):
        context = super().get_context_data(**kwargs)
        return render(self.request, self.template_name, context)

    def form_valid(self, form):
        form.instance.um = self.request.user       
        # if self.request.user.is_superuser == False and form.instance.estado_aceptacion == True:                
        #     messages.success(self.request,'Se encuentrada aceptado el gasto ') 
        #     return redirect('elim:gasto_list')
        # if perfil:=PerfilConductor.objects.filter(usuario = self.request.user).first():
        #     vehiculo = Vehiculo.objects.get(placa=perfil.vehiculo)
        #     if vehiculo and self.request.user.is_superuser:            
        #         if form.instance.estado_aceptacion is None:                
        #             form.instance.usuario_aceptacion = None
        #             form.instance.usuario_rechazo = None
        #         elif bool(form.instance.estado_aceptacion):                
        #             form.instance.usuario_aceptacion = self.request.user.username                
        #         else:                
        #             form.instance.usuario_rechazo = self.request.user.username        
        #     elif vehiculo and self.request.user.is_superuser == False:                                        
        #         form.instance.cedula = vehiculo.conductor.cedula
        #         form.instance.conductor = vehiculo.conductor.nombre
        return super().form_valid(form)

srv/templates/servicio/servicio_detail.html
{% load static %}
<div >
    <div>
        <div >
            <h4 class="modal-title">Servicio, {{obj.id}} <span> </span></h4>
            <button type="button" class="close" onclick="return cerrar_modal()">&times;</button>
        </div>
        {{obj.fecha}}
        {{obj.content}}
        <div >
            <!-- <picture>

            </picture> -->
        </div>
        <div >
            <button onclick="return cerrar_modal()" type="button" class="btn btn-success"
                data-dismiss="modal">Cerrrar</button>
        </div>
    </div>
</div>


{% block js_page %}


<script>
    $(function () {
        // console.log("{{obj}}")
    });
</script>

{% endblock %}

srv/templates/servicio/servicio_list.html
{% extends 'base/base.html' %}
{% block page_content %}
{% load humanize %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Servicios</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'srv:servicio_new' %}">
                    <i class="far fa-calendar-plus"></i> Nuevo</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        <!-- <div class="titleholder"> -->
            <!-- <div class="title text-uppercase"> Vehiculos Elim Logística</div> -->
            <!-- <div class="title"> {% if location %} para {{location.direccion}} ({{label}}) {% endif %}</div>  -->
        <!-- </div> -->

        <!-- Card menu -->
        <div class="alert alert-info">            
            <a class="btn btn-default" href="{% url 'srv:servicio_new' %}" >
                <i class="far fa-comment"></i>
                Registrar servicio 
            </a>
        </div>
        {% if not obj %}
        <div class="alert alert-info"> Ningún servicio disponible </div>
        {% endif %}
        <div class="row">
            <div class="col">
                <form action="{% url 'srv:servicio_list' %}" method="get">                    
                    <div class="col-md-12">
                        <div class="col-md-3">
                            Fecha:{{form.fecha}}
                        </div>
                        <div class="row mt-2">
                            <div class="col">
                                <div class="col-md-12">                    
                                    <button  type="submit" class="btn btn-primary">
                                        <span class="fa fa-filter"></span> 
                                        filtrar
                                    </button>
                                    <a href="{% url 'srv:servicio_list' %}" class="btn btn-danger">
                                        <span class="fa fa-trash"></span>  
                                        limpiar                                       
                                    </a>                        
                                </div>
                            </div>  
                        </div>
                    </div>
                </form>
            </div>
        </div>     

        <div class="row">
            <div class="col">
                        
            </div>
        </div>
        <div class="dropdown-divider"></div>
        <table id="table" class="table table-striped table-hover dt-responsive mb-5" style="height: 100%;">
            <thead>
                <th class="all"> </th>
                <th>Dispositivo</th>                
                <th>Tecnico</th>  
                <th>Estado</th> 
                <th>Sede</th> 
                <th>Concepto</th>
                <th>Fecha</th> 
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                  <td>
                    <a href="{% url 'srv:servicio_edit' item.id %}" class="" role="button">
                      <i class="far fa-edit"> </i>
                    </a> 
                    <!-- <a href="{#% url 'srv:servicio_del' item.id %#}" class="btn btn-danger btn-circle" role="button">
                      <i class="far fa-trash-alt"></i>
                    </a> -->
                  </td>
                  <td class="align-baseline text-bg-primary text-wrap text-star" style="width: 6rem;">
                    {{ item.dispositive }}
                  </td>
                  <td>{{ item.technic | upper }}</td>
                  <td>{{ item.status | upper }}</td>
                  <td>{{ item.sede }}</td>
                  <!-- <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td> -->
                  <td >
                    <p class=" text-wrap align-baseline text-bg-primary  text-star" style="width: 30rem;" >                    
                        {{ item.content}}
                    </p>
                   </td>
                  <td>{{ item.fecha|date:"d/m/Y H:i:s" }}</td>
                </tr>
                {% endfor %}

            </tbody>
            <tfoot>
                <tr>
                    <th colspan="4" style="text-align:left" >Total:<div id="id_total">0.0</div> </th>
                    <th></th>
                </tr>
            </tfoot>
        </table>        
    </div>
</div>

{% endblock %}
{% block js_page %}
<script>
        $(document).ready(function () {
            $('.table').DataTable(
                {
                    paging: true,
                    scrollCollapse: true,
                    scrollY: '1550px',
                    scrollX: true,
                    responsive: true,
                    language: {
                        "sProcessing": "Procesando...",
                        "sLengthMenu": "Mostrar _MENU_ registros",
                        "sZeroRecords": "No se encontraron resultados",
                        "sEmptyTable": "Ningún dato disponible en esta tabla",
                        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                        "sInfoPostFix": "",
                        "sSearch": "Buscar:",
                        "sUrl": "",
                        "sInfoThousands": ",",
                        "sLoadingRecords": "Cargando...",
                        "oPaginate": {
                            "sFirst": "<span class='fa fa-angle-double-left'></span>",
                            "sLast": "<span class='fa fa-angle-double-right'></span>",
                            "sNext": "<span class='fa fa-angle-right'></span>",
                            "sPrevious": "<span class='fa fa-angle-left'></span>"
                        },
                        "oAria": {
                            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                        }
                    }
                }
            );
        });

            $("#id_fecha").datetimepicker({
                format: 'd/m/Y',
                timepicker: false,
            });

            let dataTable;
            let dataTableIsInitialized = false;
            const dataTableOptions = {
                columnDefs: [
                    { className: "centered", targets: [0, 1, 2, 3, 4, 5, 6] },
                    { orderable: false, targets: [0] },
                    { searchable: false, targets: [0] }
                ],
                pageLength: 10,
                destroy: true,
                stateSave: true,
                // scrollCollapse:true,
                scrollY: '280px',
                scrollX: true,
                responsive: true,
                processing: true,
                dom: 'Blfrtip',
                language: {
                    "decimal": ',',
                    "thousands": '.',
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "<span class='fa fa-angle-double-left'></span>",
                        "sLast": "<span class='fa fa-angle-double-right'></span>",
                        "sNext": "<span class='fa fa-angle-right'></span>",
                        "sPrevious": "<span class='fa fa-angle-left'></span>"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    },
                },
                // layout: {
                //     topStart: {
                //         buttons: [
                //             { extend: 'crear',  },
                //             { extend: 'editar',  },
                //             { extend: 'quitar',  }
                //         ]
                //     }
                // },
            };

        
</script>
{% endblock %}

srv/templates/servicio/servicio_view.html
{% extends 'base/base.html' %}
{% block page_content %}
  <h1>Registrar dirección</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_div}}
    <button type="submit" class="btn-outline-primary">Registrar</button>
  </form>
{% endblock page_content %}